### ISSUE TITLE
自定义端口, 重启会导致http.json被错误的重复替换

### ISSUE THREAD

**Issue by HimekoEx** [AirryCo/spt-server-ci#4]
原本`6969`
我调整成`46969`
结果重启镜像会变成`446969`, 再重启类推

**Comment by HimekoEx** [comment]
![image](https://github.com/user-attachments/assets/932be0a0-af41-4052-97d1-2f2973ebaee4)

**Comment by HimekoEx** [comment]
docker compose file

```yaml
services:
  spt-server:
    image: stblog/spt-server:3.10.0
    container_name: spt-server
    restart: unless-stopped
    volumes:
      - /root/spt_server_data:/opt/spt-server
    ports:
      - '46969:46969'
    environment:
      - TZ=Asia/Shanghai
      - backendIp=xxx.xxx.xxx.xxx
      - backendPort=46969
```
